# Generated by Django 6.0.4 on 2026-04-21 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('category', models.CharField(choices=[('visitor', 'Visitor'), ('rotarian', 'Rotarian'), ('rotaractor', 'Rotaractor'), ('guest', 'Guest'), ('other', 'Other')], default='visitor', max_length=20)),
                ('rotary_club', models.CharField(blank=True, max_length=180)),
                ('rotaract_club', models.CharField(blank=True, max_length=180)),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('additional_comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=180)),
                ('event_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('qr', 'QR Code'), ('link', 'Direct Link'), ('manual', 'Manual')], default='link', max_length=20)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.event')),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'attendee'), name='unique_attendance_per_event')],
            },
        ),
    ]
