# Generated by Django 6.0.4 on 2026-04-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='category',
            field=models.CharField(choices=[('usual_suspect', 'Usual Suspect :)'), ('keb_member', 'KEB Member'), ('rotarian_other_club', 'Rotarian (Other Club)'), ('rotaractor', 'Rotaractor'), ('guest', 'Guest')], default='usual_suspect', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='communication_preference',
            field=models.CharField(choices=[('email', 'Email'), ('tel', 'Tel'), ('both', 'Both'), ('none', 'None')], default='both', max_length=20),
        ),
    ]
