# Generated by Codex on 2026-04-22

from django.db import migrations


def normalize_choice_values(apps, schema_editor):
    Attendee = apps.get_model("attendance", "Attendee")

    category_map = {
        "visitor": "usual_suspect",
        "rotarian": "rotarian_other_club",
        "rotaractor": "rotaractor",
        "guest": "guest",
        "other": "keb_member",
    }
    communication_map = {
        "phone": "tel",
        "whatsapp": "both",
        "sms": "tel",
        "email": "email",
    }

    for attendee in Attendee.objects.all():
        updated = False

        next_category = category_map.get(attendee.category, attendee.category)
        if attendee.category != next_category:
            attendee.category = next_category
            updated = True

        next_communication = communication_map.get(
            attendee.communication_preference, attendee.communication_preference
        )
        if attendee.communication_preference != next_communication:
            attendee.communication_preference = next_communication
            updated = True

        if updated:
            attendee.save(update_fields=["category", "communication_preference"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_alter_attendee_category_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_choice_values, noop_reverse),
    ]
