# Generated by Django 6.0.4 on 2026-04-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendee_receive_future_emails_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_event',
        ),
        migrations.AddField(
            model_name='event',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='attendance.formtemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_link_active',
            field=models.BooleanField(default=True),
        ),
    ]
