# Generated by Django 6.0.4 on 2026-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_unique_attendance_per_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='receive_future_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='receive_future_emails',
            field=models.BooleanField(default=True),
        ),
    ]
